def get_ide_description():
    ide_description_list = [
        '- Visual Studio Code: Visual Studio Code is a lightweight and versatile code editor developed by Microsoft. It offers a wide range of features and extensions that enhance the coding experience. With its intuitive interface, powerful editing capabilities, and integrated debugging tools, Visual Studio Code is popular among developers for various programming languages.',
        '- Jupyter Notebook: Jupyter Notebook is an open-source web application that allows users to create and share documents containing live code, equations, visualizations, and narrative text. It supports multiple programming languages and provides an interactive environment for data analysis, scientific computing, and machine learning. Jupyter Notebook promotes reproducible research and facilitates collaboration among researchers and data scientists.',
        '- PyCharm: PyCharm is a comprehensive integrated development environment (IDE) specifically designed for Python development. Developed by JetBrains, PyCharm offers a wide range of features such as code completion, debugging, version control integration, and intelligent code analysis. It provides a user-friendly interface and supports web development frameworks like Django and Flask, making it a popular choice among Python developers.']
    return ide_description_list


def get_version_control_description():
    version_control_description_list = [
'- Bitbucket ist ein webbasierter Onlinedienst zur Versionsverwaltung für Software-Entwicklungsprojekte',
'- GitHub is a web-based hosting service for version control using Git. It provides a platform for developers to collaborate on projects, contribute to open-source software, and showcase their work. GitHub offers features like pull requests, issue tracking, and project management tools. It has a large community of developers and offers seamless integration with various development tools, making it a widely used platform for code collaboration and sharing.',
'- Git is a distributed version control system that allows developers to track changes in their codebase. It provides a decentralized approach to version control, enabling multiple developers to work on the same project simultaneously. Git offers features like branching, merging, and history tracking, making it efficient for managing code changes and collaborating with others. It is widely used in software development to ensure code integrity and facilitate team collaboration.',
'- SVN (Subversion) is a centralized version control system that helps developers track changes in their codebase. It provides a centralized repository where developers can commit their changes and retrieve previous versions of files. SVN offers features like branching, merging, and access control. While it is less popular compared to Git, SVN is still used in certain industries and organizations that prefer a centralized approach to version control.']
    return version_control_description_list


def get_programming_languages():
    return [
        '- Python3 is a high-level programming language known for its simplicity and readability. It offers a vast standard library and supports multiple programming paradigms, making it versatile for various applications. Python3 is widely used in web development, data analysis, artificial intelligence, and automation tasks. Its clean syntax and extensive community support make it a popular choice among developers.',
        '- HTML (Hypertext Markup Language) is the standard markup language used for creating web pages and applications. It provides the structure and content of a webpage, defining elements such as headings, paragraphs, images, links, and tables. HTML is the backbone of the web and is essential for building static web pages and working in conjunction with other technologies like CSS and JavaScript.',
        '- CSS (Cascading Style Sheets) is a style sheet language used to describe the presentation and formatting of a document written in HTML. It allows developers to control the layout, colors, fonts, and other visual aspects of a webpage. CSS enables the separation of content and design, making it easier to maintain and update the appearance of multiple web pages simultaneously.',
        '- SQL (Structured Query Language) is a programming language used for managing and manipulating relational databases. It provides a standardized way to interact with databases, allowing users to create, retrieve, update, and delete data. SQL is essential for tasks such as data analysis, database administration, and building dynamic web applications that rely on storing and retrieving structured data.',
        '- NoSQL (Not Only SQL) is a type of database management system that provides a non-relational approach to data storage and retrieval. Unlike traditional SQL databases, NoSQL databases are designed to handle large volumes of unstructured or semi-structured data. They offer flexibility, scalability, and high performance, making them suitable for applications with rapidly changing data requirements, such as social media platforms, IoT devices, and real-time analytics.']


def get_python_libs_description():
    return [
        '- Pandas is a powerful open-source data manipulation and analysis library for Python. It provides data structures and functions to efficiently handle and analyze structured data, such as tables and time series. Pandas is widely used in data science and data analysis tasks, offering functionalities for data cleaning, transformation, aggregation, and visualization.',
        '- Polars is a fast and efficient data manipulation library for Python and Rust. It aims to provide a similar interface to Pandas but with improved performance for large-scale data processing. Polars supports columnar data structures and offers a wide range of operations for data manipulation, filtering, aggregation, and joins.',
        '- NumPy is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in fields such as data analysis, machine learning, and numerical simulations.',
        '- Tkinter is the standard Python interface for creating graphical user interfaces (GUI). It provides a set of tools and widgets to build desktop applications with a native look and feel. Tkinter is easy to use and allows developers to create windows, buttons, menus, and other GUI elements to interact with users.',
        '- PyQt is a set of Python bindings for the Qt application framework. It enables developers to create cross-platform desktop applications with rich graphical interfaces. PyQt provides a wide range of widgets, layout managers, and event handling mechanisms to build interactive and visually appealing applications.',
        '- asammdf is a Python library for reading, writing, and analyzing MDF (Measurement Data Format) files. MDF is a common file format used in automotive and other industries to store measurement data. asammdf allows users to extract, manipulate, and visualize data from MDF files, making it useful for tasks such as data analysis and signal processing.',
        '- python-pptx is a Python library for creating and updating PowerPoint (.pptx) files. It provides a simple and intuitive API to generate slides, add text, images, tables, charts, and other elements to PowerPoint presentations. python-pptx allows users to automate the creation of professional-looking slideshows and customize them programmatically.',
        '- Plotly is a data visualization library that allows users to create interactive and visually appealing charts, graphs, and dashboards. It supports various programming languages and offers a wide range of customization options, making it suitable for both exploratory data analysis and production-ready visualizations.',
        '- Matplotlib is a popular plotting library for Python that provides a wide range of static, animated, and interactive visualizations. It offers a flexible API and supports various plot types, including line plots, scatter plots, bar plots, and more. Matplotlib is widely used in scientific computing and data analysis.',
        '- Pandera is a lightweight data validation library for Python. It allows users to define and enforce data validation rules on pandas DataFrames, ensuring data quality and consistency. Pandera provides an expressive syntax and integrates well with other data manipulation libraries.',
        '- Pydantic is a data validation and parsing library for Python. It allows users to define data schemas using Python classes and provides automatic data validation, serialization, and deserialization. Pydantic is commonly used in API development and data processing pipelines.',
        '- Selenium is a popular open-source framework for automating web browsers. It provides a set of tools and libraries for browser automation and testing. Selenium allows users to interact with web elements, simulate user actions, and perform automated testing of web applications.',
        '- XlsxWriter is a Python library for creating Excel files in the XLSX file format. It provides a simple and intuitive API for writing data, formatting cells, and creating charts in Excel spreadsheets. XlsxWriter is widely used for generating reports and exporting data from Python to Excel.',
        '- OpenPyXL is a Python library for reading and writing Excel files in the XLSX file format. It allows users to manipulate Excel spreadsheets, including creating, modifying, and extracting data. OpenPyXL supports various Excel features and provides an easy-to-use interface.',
        '- Hypothesis is a powerful property-based testing library for Python. It allows users to define properties and generate test cases automatically based on those properties. Hypothesis helps in finding edge cases and potential bugs in code by generating a wide range of test inputs.',
        '- Pytest is a popular testing framework for Python. It provides a simple and intuitive way to write tests, allowing users to focus on writing test cases rather than boilerplate code. Pytest supports various testing features, including test discovery, fixtures, parameterization, and test coverage.',
        '- itertools is a module in the Python standard library that provides various functions for efficient iteration and combination of iterable objects. It offers a collection of tools for creating iterators, combining multiple iterables, and performing common data manipulation tasks.',
        '- Dash is a Python framework for building web applications with interactive data visualizations. It allows users to create interactive dashboards, reports, and data-driven applications using Python and web technologies. Dash provides a declarative syntax and integrates well with Plotly for creating interactive visualizations.',
        '- Streamlit is a Python library for building interactive web applications for data science and machine learning. It simplifies the process of creating and deploying data-driven applications by providing an intuitive API and automatic rendering of data visualizations. Streamlit is designed to be easy to use and requires minimal code to create interactive apps.']

